config/routes.rb
Rails.application.routes.draw do
  resources :monas
  root 'monas#index'

end

app/models/mona.rb
class Mona < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/monas_controller.rb
class MonasController < ApplicationController
  before_action :set_mona, only: [:show, :edit, :update, :destroy]

  # GET /monas
  # GET /monas.json
  def index
    @monas = Mona.all
  end

  # GET /monas/1
  # GET /monas/1.json
  def show
  end

  # GET /monas/new
  def new
    @mona = Mona.new
  end

  # GET /monas/1/edit
  def edit
  end

  # POST /monas
  # POST /monas.json
  def create
    @mona = Mona.new(mona_params)

    respond_to do |format|
      if @mona.save
        format.html { redirect_to @mona, notice: 'Mona was successfully created.' }
        format.json { render :show, status: :created, location: @mona }
      else
        format.html { render :new }
        format.json { render json: @mona.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /monas/1
  # PATCH/PUT /monas/1.json
  def update
    respond_to do |format|
      if @mona.update(mona_params)
        format.html { redirect_to @mona, notice: 'Mona was successfully updated.' }
        format.json { render :show, status: :ok, location: @mona }
      else
        format.html { render :edit }
        format.json { render json: @mona.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /monas/1
  # DELETE /monas/1.json
  def destroy
    @mona.destroy
    respond_to do |format|
      format.html { redirect_to monas_url, notice: 'Mona was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mona
      @mona = Mona.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mona_params
      params[:mona]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/monas_helper.rb
module MonasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Arceline</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/monas/_form.html.erb
<%= form_for(@mona) do |f| %>
  <% if @mona.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mona.errors.count, "error") %> prohibited this mona from being saved:</h2>

      <ul>
      <% @mona.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/monas/edit.html.erb
<h1>Editing Mona</h1>

<%= render 'form' %>

<%= link_to 'Show', @mona %> |
<%= link_to 'Back', monas_path %>

app/views/monas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Monas</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @monas.each do |mona| %>
      <tr>
        <td><%= link_to 'Show', mona %></td>
        <td><%= link_to 'Edit', edit_mona_path(mona) %></td>
        <td><%= link_to 'Destroy', mona, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mona', new_mona_path %>

app/views/monas/new.html.erb
<h1>New Mona</h1>

<%= render 'form' %>

<%= link_to 'Back', monas_path %>

app/views/monas/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_mona_path(@mona) %> |
<%= link_to 'Back', monas_path %>